---

 - name: Making sure java is installed on the system
   yum: name=java state=installed
   when: "{{ install_java }}"
   tags: packages,java

 - name: Jenkins for Centos/RedHat
   yum_repository:
      name="Jenkins_Repo"
      file="jenkins"
      description="jenkins"
      baseurl="{{ centos_jenkins_repo_url }}"
      gpgkey="{{ centos_jenkins_repo_key_url }}"
      gpgcheck="yes"
      state="present"
   tags: repo

 - name: Install Jenkins 
   yum: name=jenkins state=installed
   tags: packages,jennkins
   
 - name: Setting Jenkins listenport
   lineinfile: dest=/etc/sysconfig/jenkins regexp="JENKINS_PORT=" insertafter="^JENKINS_PORT=" line="JENKINS_PORT={{ jenkins_port }}" backup=yes backrefs=yes
   register: change        
   tags: jenkins


