---
- name: Ensure dependencies are installed.
  apt:  name={{ item }} state=installed
  with_items:
    - curl
    - apt-transport-https
 
- name: Add Jenkins apt repository key.
  apt_key: url="{{ debian_jenkins_repo_key_url }}" state=present

# Jenkins needs some backported java packages of Debian 8/Jessie
- name: add backports repository
  apt_repository: repo='deb {{ debian_backports_url }} {{ debian_backports_components }}' update_cache=yes state=present

- name: Add Jenkins apt repository.
  apt_repository:  repo="{{ debian_jenkins_repo_url }}"  update_cache=yes state=present

- name: Install java from backports
  apt: name={{ item }} default_release=jessie-backports update_cache=yes state=present
  with_items:
   - openjdk-8-jre-headless
   - ca-certificates-java
  when: "{{ install_java }}"

- name: Install jenkins 
  apt:  name=jenkins state=present
