---
 - include: centos.yml
   when: ansible_os_family == "RedHat"
   tags: jenkins

 - include: debian.yml
   when: ansible_os_family == "Debian"
   tags: jenkins

 - name: Enabling and starting Jenkins
   service: name=jenkins state=started enabled=true
   tags: service,jenkins     

 - name: Restart jenkins when change
   service: name=jenkins state=restarted
   when: change.changed
   tags: service,jenkins        